#  Pipeline for frontend
stages:
  - build

build-code:
  stage: build
  image: ubuntu:20.04
  script:
    - sudo apt update
    - >
      sudo apt install -y python3-pip python3-setuptools python3-wheel ninja-build \
      build-essential flex bison git cmake libsctp-dev libgnutls28-dev libgcrypt-dev \
      libssl-dev libidn11-dev libmongoc-dev libbson-dev libyaml-dev libnghttp2-dev \
      libmicrohttpd-dev libcurl4-gnutls-dev libnghttp2-dev libtins-dev libtalloc-dev meson
    - meson build --prefix=`pwd`/install && meson --reconfigure -Dmetrics_impl=prometheus build
    - ninja -C build
    - cd build
    - meson test -v
    - ninja install
    - ll install/etc/open5gs/*
