stages:
  - module-pipelines
  - test
  # - deploy

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SAST_EXCLUDED_ANALYZERS: "brakeman,flawfinder,nodejs-scan,semgrep,spotbugs"

build-docker-images:
  stage: module-pipelines
  trigger:
    include:
      - "/openms/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - openms/**/*
      