# Pipeline for frontend
stages:
  - build
  - test

include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SAST_EXCLUDED_ANALYZERS: "brakeman,flawfinder,nodejs-scan,semgrep,spotbugs"

default:
  cache:
    key: "build-code-$CI_COMMIT_REF_SLUG"
    paths:
      - install/bin/open5gs-*

build-code:
  stage: build
  image: mongo:jammy
  variables: 
    DEBIAN_FRONTEND: "noninteractive"
  script:
    - apt-get update
    - |
      apt-get install -y python3-pip python3-setuptools python3-wheel ninja-build \
      build-essential flex bison git cmake libsctp-dev libgnutls28-dev libgcrypt-dev \
      libssl-dev libidn11-dev libmongoc-dev libbson-dev libyaml-dev libnghttp2-dev \
      libmicrohttpd-dev libcurl4-gnutls-dev libnghttp2-dev libtins-dev libtalloc-dev meson \
      gnupg curl iproute2
    - ip tuntap add name ogstun mode tun
    - ip addr add 10.45.0.1/16 dev ogstun
    - ip addr add 2001:db8:cafe::1/48 dev ogstun
    - ip link set ogstun up
    - |
      meson build --prefix=`pwd`/install && meson --reconfigure -Dmetrics_impl=prometheus build
      ninja -C build
      cd build
      meson test -v
      ninja install
      ll install/etc/open5gs/*
  cache:
    key: "build-code-$CI_COMMIT_REF_SLUG"
    paths:
      - install/bin/open5gs-*
