stages:
  - build
  - release

# include:
#   - project: 'templates/ci'
#     file: 'DockerInDockerTemplate.yml'

build-docker-images:
  stage: build
  image: docker:24.0.6-dind
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - until docker info; do sleep 1; done
    - echo "${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}:${CI_REGISTRY}"
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - cd openms/docker
    - >
      docker build
      --file Dockerfile_mongodb
      --tag ${CI_REGISTRY_IMAGE}/open5gs-mongodb:${CI_COMMIT_SHORT_SHA} 
      .
    - docker push ${CI_REGISTRY_IMAGE}/open5gs-mongodb:${CI_COMMIT_SHORT_SHA}

upload-docker-image-latest:
  stage: release
  variables:
    GIT_STRATEGY: none
  image: docker:24.0.6-dind
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  when: on_success
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/open5gs-mongodb:${CI_COMMIT_SHORT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}/open5gs-mongodb:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}/open5gs-mongodb:latest
    - docker push ${CI_REGISTRY_IMAGE}/open5gs-mongodb:latest

